project 'device tracking 1.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'device tracking 1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for device tracking 1

  source 'https://github.com/CocoaPods/Specs.git'
  #target 'device tracking 1' do
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  #end
  
  target 'device tracking 1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
